# Generated by Django 6.0.1 on 2026-05-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='company_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
