# Generated by Django 6.0.1 on 2026-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='amount_wanted_to_borrow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='borrowing_from_licensed_lender',
            field=models.CharField(blank=True, choices=[('YES', 'Yes / Ya'), ('NO', 'No / Tidak')], max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='car_loan_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='has_other_income',
            field=models.CharField(blank=True, choices=[('YES', 'Yes / Ya'), ('NO', 'No / Tidak')], max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='has_other_loans',
            field=models.CharField(blank=True, choices=[('YES', 'Yes / Ya'), ('NO', 'No / Tidak')], max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='house_loan_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='licensed_lender_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='loan_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single / Bujang'), ('MARRIED', 'Married / Berkahwin'), ('WIDOW', 'Widow / Janda')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='motorcycle_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='net_salary_after_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='number_of_working_children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='other_commitment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_commitment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='other_income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_income_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='referred_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='salary_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='salary_bank_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='spouse_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='spouse_ic_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='spouse_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='spouse_job',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='support_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='support_status',
            field=models.CharField(blank=True, choices=[('SUPPORT', 'Support'), ('NOT_SUPPORT', 'Not Support')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='total_working_years',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
