# Generated by Django 6.0.1 on 2026-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_amount_wanted_to_borrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_converted_to_customer',
            field=models.BooleanField(default=False),
        ),
    ]
