# Generated by Django 6.0.1 on 2026-06-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application_is_converted_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mykad_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mykad_photos/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
