# Generated by Django 6.0.1 on 2026-06-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_customer_number_customer_customer_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_address_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_address_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_address_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_working_years',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='working_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
