# Generated by Django 6.0.1 on 2026-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_balance_transfer_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
