# Generated by Django 6.0.1 on 2026-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customer_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='house_rental_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
