# Generated by Django 6.0.1 on 2026-06-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_house_rental_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='other_vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
