# Generated by Django 6.0.1 on 2026-06-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customer_other_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='other_vehicle_type',
        ),
    ]
