# Generated by Django 6.0.1 on 2026-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_customer_other_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
