# Generated by Django 6.0.1 on 2026-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customer_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='created_by',
        ),
        migrations.AddField(
            model_name='agreement',
            name='interest_rate_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='interest_rate_words',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='monthly_repayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='principal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='principal_amount_words',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agreement',
            name='total_repayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
