# Generated by Django 6.0.1 on 2026-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_agreement_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='book',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
