# Generated by Django 6.0.1 on 2026-07-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_messagetemplate_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='key',
            field=models.CharField(choices=[('PRE_REGISTER', 'Pre-registration Link'), ('LOGIN_TEMP_PASSWORD', 'Staff Login + Temporary Password'), ('CUSTOMER_REMINDER', 'Customer Reminder'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('CUSTOM', 'Custom Message'), ('USER', 'User-created Template')], max_length=50),
        ),
    ]
